spring:
  application:
    name: clima
  redis:
    host: redis
    port: 6379
    password: ${REDIS_PASSWORD}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASS}

cache:
  weather:
    ttl-minutes: 15

server:
  port: 0

weatherstack:
  api-key: ${WEATHER_API_KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-service-url-poll-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASS}@discovery:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false

mq:
  queue:
    clima-request: clima-request
    clima-response: clima-response